version: "3"
services:
 app:
  build: .
  container_name: test
  volumes:
   - ./app:/var/www/html/app
  ports:
   - "8888:80"
  tty:
   true
  deploy:
     resources:
      reservations:
       devices:
        - driver: nvidia
          capabilities: [gpu]